USE `clfc2`;

CREATE TABLE IF NOT EXISTS `amnesty` (
  `objid` varchar(50) NOT NULL,
  `txnstate` varchar(25) default NULL COMMENT 'DRAFT,FOR_APPROVAL,APPROVED,DISAPPROVED,CLOSED',
  `txnmode` varchar(25) default NULL COMMENT 'ONLINE,CAPTURE',
  `dtcreated` datetime default NULL,
  `author_objid` varchar(50) default NULL,
  `author_name` varchar(50) default NULL,
  `txndate` date default NULL,
  `refno` varchar(25) default NULL,
  `ledgerid` varchar(50) default NULL,
  `txntype` varchar(25) default NULL COMMENT 'AVAIL,REJECT',
  `borrower_objid` varchar(50) default NULL,
  `borrower_name` varchar(50) default NULL,
  `loanapp_objid` varchar(50) default NULL,
  `loanapp_appno` varchar(50) default NULL,
  `dtstarted` date default NULL,
  `dtended` date default NULL,
  `amnestyoption` varchar(25) default NULL COMMENT 'WAIVER,FIX',
  `iswaiveinterest` smallint(3) default '0',
  `iswaivepenalty` smallint(3) default '0',
  `remarks` varchar(255) default NULL,
  `grantedoffer_amount` decimal(10,2) default '0.00',
  `grantedoffer_days` smallint(3) default '0',
  `grantedoffer_months` smallint(3) default '0',
  `grantedoffer_isspotcash` smallint(3) default '0',
  `grantedoffer_date` date default NULL,
  `dtposted` datetime default NULL,
  `poster_objid` varchar(50) default NULL,
  `poster_name` varchar(50) default NULL,
  `poster_remarks` varchar(255) default NULL,
  `version` smallint(3) default '1',
  `extendeddate` date default NULL,
  `balance` decimal(10,2) default '0.00',
  PRIMARY KEY  (`objid`),
  UNIQUE KEY `uix_refno_version` (`refno`,`version`),
  KEY `ix_txnstate` (`txnstate`),
  KEY `ix_dtcreated` (`dtcreated`),
  KEY `ix_authorid` (`author_objid`),
  KEY `ix_refno` (`refno`),
  KEY `ix_ledgerid` (`ledgerid`),
  KEY `ix_borrowerid` (`borrower_objid`),
  KEY `ix_loanappid` (`loanapp_objid`),
  KEY `ix_loanappno` (`loanapp_appno`),
  KEY `ix_dtstarted` (`dtstarted`),
  KEY `ix_dtended` (`dtended`),
  KEY `ix_iswaiveinterest` (`iswaiveinterest`),
  KEY `ix_iswaivepenalty` (`iswaivepenalty`),
  KEY `ix_dtposted` (`dtposted`),
  KEY `ix_posterid` (`poster_objid`),
  KEY `ix_version` (`version`),
  KEY `ix_extendeddate` (`extendeddate`),
  KEY `ix_txndate` (`txndate`),
  KEY `ix_amnestyoption` (`amnestyoption`),
  KEY `ix_txntype` (`txntype`),
  KEY `ix_grantedofferisspotcash` (`grantedoffer_isspotcash`),
  KEY `ix_grantedofferdate` (`grantedoffer_date`),
  KEY `ix_txnmode` (`txnmode`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `amnesty_active` (
  `objid` varchar(50) NOT NULL,
  PRIMARY KEY  (`objid`),
  CONSTRAINT `fk_amnesty_active` FOREIGN KEY (`objid`) REFERENCES `amnesty` (`objid`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `amnesty_detail` (
  `objid` varchar(50) NOT NULL,
  `parentid` varchar(50) default NULL,
  `state` varchar(25) default NULL,
  `amtdue` decimal(10,2) default '0.00',
  `interestdue` decimal(10,2) default '0.00',
  `penaltydue` decimal(10,2) default '0.00',
  `amtpaid` decimal(10,2) default '0.00',
  `interestpaid` decimal(10,2) default '0.00',
  `penaltypaid` decimal(10,2) default '0.00',
  `amtbal` decimal(10,2) default '0.00',
  `interestbal` decimal(10,2) default '0.00',
  `penaltybal` decimal(10,2) default '0.00',
  `dtpaid` date default NULL,
  `refno` varchar(25) default NULL,
  `day` smallint(6) default NULL,
  `balance` decimal(16,2) default '0.00',
  `partialpayment` decimal(10,2) default '0.00',
  `txndate` datetime default NULL,
  `remarks` text,
  PRIMARY KEY  (`objid`),
  KEY `ix_state` (`state`),
  KEY `ix_dtpaid` (`dtpaid`),
  KEY `ix_refno` (`refno`),
  KEY `ix_day` (`day`),
  KEY `ix_txndate` (`txndate`),
  KEY `fk_amnesty_detail` (`parentid`),
  CONSTRAINT `fk_amnesty_detail` FOREIGN KEY (`parentid`) REFERENCES `amnesty` (`objid`)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS `amnesty_extension` (
  `objid` varchar(50) NOT NULL,
  `txnstate` varchar(50) default NULL COMMENT 'DRAFT,FOR_APPROVAL,APPROVED,DISAPPROVED',
  `dtcreated` datetime default NULL,
  `author_objid` varchar(50) default NULL,
  `author_name` varchar(50) default NULL,
  `txndate` date default NULL,
  `refno` varchar(25) default NULL,
  `amnesty_objid` varchar(50) default NULL,
  `amnesty_refno` varchar(25) default NULL,
  `amnesty_dtstarted` date default NULL,
  `amnesty_dtended` date default NULL,
  `amnesty_amount` decimal(10,2) default '0.00',
  `borrower_objid` varchar(50) default NULL,
  `borrower_name` varchar(50) default NULL,
  `extendeddate` date default NULL,
  `extendeddays` smallint(3) default '0',
  `remarks` varchar(255) default NULL,
  `dtposted` datetime default NULL,
  `poster_objid` varchar(50) default NULL,
  `poster_name` varchar(50) default NULL,
  `poster_remarks` varchar(255) default NULL,
  PRIMARY KEY  (`objid`),
  KEY `ix_txnstate` (`txnstate`),
  KEY `ix_dtcreated` (`dtcreated`),
  KEY `ix_authorid` (`author_objid`),
  KEY `ix_txndate` (`txndate`),
  KEY `ix_amnestyid` (`amnesty_objid`),
  KEY `ix_amnestydtstarted` (`amnesty_dtstarted`),
  KEY `ix_amnestydtended` (`amnesty_dtended`),
  KEY `ix_extendeddate` (`extendeddate`),
  KEY `ix_exntededdays` (`extendeddays`),
  KEY `ix_dtposted` (`dtposted`),
  KEY `ix_posterid` (`poster_objid`),
  KEY `ix_refno` (`refno`),
  KEY `ix_borrowerid` (`borrower_objid`),
  KEY `ix_amnestyrefno` (`amnesty_refno`),
  CONSTRAINT `fk_amnesty_extension` FOREIGN KEY (`amnesty_objid`) REFERENCES `amnesty` (`objid`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `amnesty_history` (
  `objid` varchar(50) NOT NULL,
  `dtcreated` datetime default NULL,
  `author_objid` varchar(50) default NULL,
  `author_name` varchar(50) default NULL,
  `txndate` date default NULL,
  `refno` varchar(25) default NULL,
  `ledgerid` varchar(50) default NULL,
  `borrower_objid` varchar(50) default NULL,
  `borrower_name` varchar(50) default NULL,
  `loanapp_objid` varchar(50) default NULL,
  `loanapp_appno` varchar(25) default NULL,
  `dtstarted` date default NULL,
  `dtended` date default NULL,
  `amnestyoption` varchar(25) default NULL COMMENT 'WAIVER,FIX',
  `iswaiveinterest` smallint(3) default '0',
  `iswaivepenalty` smallint(3) default '0',
  `remarks` varchar(255) default NULL,
  `grantedoffer_amount` decimal(10,2) default '0.00',
  `grantedoffer_days` smallint(3) default '0',
  `grantedoffer_months` smallint(3) default '0',
  `grantedoffer_isspotcash` smallint(3) default '0',
  `grantedoffer_date` date default NULL,
  `dtposted` datetime default NULL,
  `poster_objid` varchar(50) default NULL,
  `poster_name` varchar(50) default NULL,
  `poster_remarks` varchar(255) default NULL,
  `version` smallint(3) default '0',
  `extendeddate` date default NULL,
  `info` text,
  `dtamended` datetime default NULL,
  `amendedby_objid` varchar(50) default NULL,
  `amendedby_name` varchar(50) default NULL,
  PRIMARY KEY  (`objid`),
  UNIQUE KEY `ix_refno_version` (`refno`,`version`),
  KEY `ix_dtcreated` (`dtcreated`),
  KEY `ix_authorid` (`author_objid`),
  KEY `ix_refno` (`refno`),
  KEY `ix_ledgerid` (`ledgerid`),
  KEY `ix_borrowerid` (`borrower_objid`),
  KEY `ix_loanappid` (`loanapp_objid`),
  KEY `ix_loanappno` (`loanapp_appno`),
  KEY `ix_dtstarted` (`dtstarted`),
  KEY `ix_dtended` (`dtended`),
  KEY `ix_iswaiveinterest` (`iswaiveinterest`),
  KEY `ix_iswaivepenalty` (`iswaivepenalty`),
  KEY `ix_dtposted` (`dtposted`),
  KEY `ix_posterid` (`poster_objid`),
  KEY `ix_version` (`version`),
  KEY `ix_extendeddate` (`extendeddate`),
  KEY `ix_dtamended` (`dtamended`),
  KEY `ix_amendedbyid` (`amendedby_objid`),
  KEY `ix_txndate` (`txndate`),
  KEY `ix_grantedofferisspotcash` (`grantedoffer_isspotcash`),
  KEY `ix_grantedofferdate` (`grantedoffer_date`),
  KEY `ix_amnestyoption` (`amnestyoption`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `amnesty_offer` (
  `objid` varchar(50) NOT NULL,
  `parentid` varchar(50) default NULL,
  `amount` decimal(10,2) default '0.00',
  `days` smallint(3) default '0',
  `months` smallint(3) default '0',
  `isspotcash` smallint(3) default '0',
  `date` date default NULL,
  PRIMARY KEY  (`objid`),
  KEY `ix_amount` (`amount`),
  KEY `ix_days` (`days`),
  KEY `ix_months` (`months`),
  KEY `fk_amnesty_offer` (`parentid`),
  KEY `ix_isspotcash` (`isspotcash`),
  KEY `ix_date` (`date`),
  CONSTRAINT `fk_amnesty_offer` FOREIGN KEY (`parentid`) REFERENCES `amnesty` (`objid`)
) ENGINE=InnoDB;



