USE `clfc2`;

CREATE TABLE IF NOT EXISTS `overagefund` (
  `objid` varchar(50) NOT NULL,
  `state` varchar(25) default NULL,
  `dtcreated` datetime default NULL,
  `author_objid` varchar(50) default NULL,
  `author_name` varchar(50) default NULL,
  `year` smallint(6) default '0',
  `amtbalance` decimal(10,2) default '0.00',
  `amtuse` decimal(10,2) default '0.00',
  PRIMARY KEY  (`objid`),
  KEY `ix_state` (`state`),
  KEY `ix_dtcreated` (`dtcreated`),
  KEY `ix_authorid` (`author_objid`),
  KEY `ix_amtbalance` (`amtbalance`),
  KEY `ix_amtuse` (`amtuse`),
  KEY `ix_year` (`year`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `overagefund_detail` (
  `objid` varchar(50) NOT NULL,
  `parentid` varchar(50) default NULL,
  `txnstate` varchar(25) default NULL COMMENT 'DRAFT,FOR_APPROVAL,APPROVED,DISAPPROVED',
  `dtcreated` datetime default NULL,
  `author_objid` varchar(50) default NULL,
  `author_name` varchar(50) default NULL,
  `txndate` date default NULL,
  `refno` varchar(25) default NULL,
  `overage_objid` varchar(50) default NULL,
  `overage_refno` varchar(25) default NULL,
  `overage_balance` decimal(7,2) default '0.00',
  `loanapp_objid` varchar(50) default NULL,
  `loanapp_appno` varchar(25) default NULL,
  `borrower_objid` varchar(50) default NULL,
  `borrower_name` varchar(50) default NULL,
  `amount` decimal(7,2) default '0.00',
  `remarks` varchar(255) default NULL,
  `dtposted` datetime default NULL,
  `poster_objid` varchar(50) default NULL,
  `poster_name` varchar(50) default NULL,
  PRIMARY KEY  (`objid`),
  UNIQUE KEY `uix_refno` (`refno`),
  KEY `ix_txnstate` (`txnstate`),
  KEY `ix_dtcreated` (`dtcreated`),
  KEY `ix_authorid` (`author_objid`),
  KEY `ix_txndate` (`txndate`),
  KEY `ix_overageid` (`overage_objid`),
  KEY `ix_overagerefno` (`overage_refno`),
  KEY `ix_borrowerid` (`borrower_objid`),
  KEY `ix_dtposted` (`dtposted`),
  KEY `ix_posterid` (`poster_objid`),
  KEY `fk_overagefund_detail` (`parentid`),
  KEY `ix_loanappid` (`loanapp_objid`),
  KEY `ix_loanappno` (`loanapp_appno`),
  CONSTRAINT `fk_overagefund_detail` FOREIGN KEY (`parentid`) REFERENCES `overagefund` (`objid`),
  CONSTRAINT `fk_overage_overagewithdrawal` FOREIGN KEY (`overage_objid`) REFERENCES `overage` (`objid`)
) ENGINE=InnoDB;
