/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.obo.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author dell
 */
@Template(FormPage.class)
public class NewApplicationPage extends javax.swing.JPanel {

    /**
     * Creates new form NewApplicationPage
     */
    public NewApplicationPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xTabbedPane1 = new com.rameses.rcp.control.XTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xFormPanel7 = new com.rameses.rcp.control.XFormPanel();
        lOVList1 = new com.rameses.enterprise.components.LOVList();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        jPanel2 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        orgTypeList1 = new com.rameses.entity.components.OrgTypeList();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        cTCIndividualEntryPage2 = new com.rameses.etracs.components.CTCIndividualEntryPage();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        cTCIndividualEntryPage1 = new com.rameses.etracs.components.CTCIndividualEntryPage();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xLookupField4 = new com.rameses.rcp.control.XLookupField();
        xPanel3 = new com.rameses.rcp.control.XPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        oboAddress1 = new com.rameses.gov.etracs.obo.components.OboAddress();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        cTCIndividualEntryPage3 = new com.rameses.etracs.components.CTCIndividualEntryPage();
        jPanel7 = new javax.swing.JPanel();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xLookupField5 = new com.rameses.rcp.control.XLookupField();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        cTCIndividualEntryPage4 = new com.rameses.etracs.components.CTCIndividualEntryPage();

        setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(30, 10, 10, 10));
        xTitledBorder1.setTitle("Building Details");
        xFormPanel5.setBorder(xTitledBorder1);
        xFormPanel5.setCaptionWidth(150);

        xLookupField2.setCaption("Occupancy / Building Use");
        xLookupField2.setExpression("#{entity.buildingkind.name}");
        xLookupField2.setHandler("obo_building_kind:lookup");
        xLookupField2.setName("entity.buildingkind"); // NOI18N
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField2.setRequired(true);
        xFormPanel5.add(xLookupField2);

        xLabel2.setCaption("Bldg Use Type");
        xLabel2.setDepends(new String[] {"entity.buildingkind"});
        xLabel2.setExpression("#{entity.buildingkind.use.objid}");
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel5.add(xLabel2);

        xIntegerField1.setCaption("No. of Units");
        xIntegerField1.setName("entity.numunits"); // NOI18N
        xFormPanel5.add(xIntegerField1);

        xDecimalField2.setCaption("Total Floor Area");
        xDecimalField2.setName("entity.floorarea"); // NOI18N
        xFormPanel5.add(xDecimalField2);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setPadding(new java.awt.Insets(30, 10, 10, 10));
        xTitledBorder2.setTitle("Work Details");
        xFormPanel7.setBorder(xTitledBorder2);
        xFormPanel7.setCaption("Work Details");
        xFormPanel7.setCaptionWidth(150);

        lOVList1.setCaption("Work Type");
        lOVList1.setListName("OBO_BUILDING_WORK_TYPE");
        lOVList1.setName("entity.worktype"); // NOI18N
        lOVList1.setPreferredSize(new java.awt.Dimension(0, 22));
        lOVList1.setRequired(true);
        xFormPanel7.add(lOVList1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 63));

        xTextArea1.setCaption("Project Description");
        xTextArea1.setName("entity.description"); // NOI18N
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel7.add(jScrollPane1);

        xDecimalField1.setCaption("Project Cost");
        xDecimalField1.setName("entity.projectcost"); // NOI18N
        xDecimalField1.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel7.add(xDecimalField1);

        xDateField1.setCaption("Proposed Construction date");
        xDateField1.setName("entity.constructiondate"); // NOI18N
        xFormPanel7.add(xDateField1);

        xDateField2.setCaption("Expected completion date");
        xDateField2.setName("entity.completiondate"); // NOI18N
        xFormPanel7.add(xDateField2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addComponent(xFormPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        xTabbedPane1.addTab("Project Information", jPanel3);

        xFormPanel1.setCaptionWidth(150);

        orgTypeList1.setCaption("Ownership Type");
        orgTypeList1.setName("entity.orgtype"); // NOI18N
        orgTypeList1.setPreferredSize(new java.awt.Dimension(0, 22));
        xFormPanel1.add(orgTypeList1);

        entityLookup1.setCaption("Owner");
        entityLookup1.setName("entity.owner"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 21));
        xFormPanel1.add(entityLookup1);

        cTCIndividualEntryPage2.setCaption("Community Tax Certificate");
        cTCIndividualEntryPage2.setDepends(new String[] {"entity.owner"});
        cTCIndividualEntryPage2.setName("entity.owner.ctc"); // NOI18N
        cTCIndividualEntryPage2.setPreferredSize(new java.awt.Dimension(0, 69));
        xFormPanel1.add(cTCIndividualEntryPage2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        xTabbedPane1.addTab("Owner Information", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        xCheckBox1.setCaption("");
        xCheckBox1.setName("entity.lotowned"); // NOI18N
        xCheckBox1.setText("Lot Owned");
        jPanel1.add(xCheckBox1, java.awt.BorderLayout.NORTH);

        xPanel1.setLayout(new java.awt.CardLayout());

        xPanel2.setDepends(new String[] {"entity.lotowned"});
        xPanel2.setVisibleWhen("#{entity.lotowned == false }");

        cTCIndividualEntryPage1.setDepends(new String[] {"entity.lotowner"});
        cTCIndividualEntryPage1.setName("entity.lotowner.ctc"); // NOI18N

        xLookupField4.setCaption("Lot Owner");
        xLookupField4.setExpression("#{entity.lotowner.name}");
        xLookupField4.setHandler("entity:lookup");
        xLookupField4.setName("entity.lotowner"); // NOI18N
        xLookupField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel4.add(xLookupField4);

        javax.swing.GroupLayout xPanel2Layout = new javax.swing.GroupLayout(xPanel2);
        xPanel2.setLayout(xPanel2Layout);
        xPanel2Layout.setHorizontalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(xFormPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cTCIndividualEntryPage1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap(640, Short.MAX_VALUE))
        );
        xPanel2Layout.setVerticalGroup(
            xPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xFormPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cTCIndividualEntryPage1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        xPanel1.add(xPanel2, "card3");

        xPanel3.setDepends(new String[] {"entity.lotowned"});
        xPanel3.setVisibleWhen("#{entity.lotowned != true }");

        javax.swing.GroupLayout xPanel3Layout = new javax.swing.GroupLayout(xPanel3);
        xPanel3.setLayout(xPanel3Layout);
        xPanel3Layout.setHorizontalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1005, Short.MAX_VALUE)
        );
        xPanel3Layout.setVerticalGroup(
            xPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        xPanel1.add(xPanel3, "card4");

        jPanel1.add(xPanel1, java.awt.BorderLayout.CENTER);

        xFormPanel2.setCaption("");
        xFormPanel2.setPreferredSize(new java.awt.Dimension(0, 100));

        xLookupField1.setCaption("TCT / OCT");
        xLookupField1.setExpression("#{entity.rptinfo.tdno}");
        xLookupField1.setHandler("lookupRpu");
        xLookupField1.setName("entity.rptinfo"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLookupField1);

        xLabel1.setCaption("PIN");
        xLabel1.setExpression("#{entity.rptinfo.fullpin}");
        xLabel1.setName("entity.rptinfo.text"); // NOI18N
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel2.add(xLabel1);

        xLabel3.setCaption("Title No");
        xLabel3.setExpression("#{entity.rptinfo.titleno}");
        xLabel3.setName("entity.rptinfo.text"); // NOI18N
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel2.add(xLabel3);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setPadding(new java.awt.Insets(30, 10, 10, 10));
        xTitledBorder3.setTitle("Project Location");
        oboAddress1.setBorder(xTitledBorder3);
        oboAddress1.setName("entity.location"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oboAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(oboAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        xTabbedPane1.addTab("Location", jPanel4);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder4 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder4.setTitle("Architect/Civil Engineer In-charge of Construction ");
        jPanel6.setBorder(xTitledBorder4);

        xFormPanel3.setCaptionWidth(180);

        xLookupField3.setCaption("Supervisor (architect/civilengineer)");
        xLookupField3.setExpression("#{entity.supervisor.name}");
        xLookupField3.setHandler("lookupSupervisor");
        xLookupField3.setName("entity.supervisor"); // NOI18N
        xLookupField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLookupField3);

        xLabel4.setCaption("Profession");
        xLabel4.setDepends(new String[] {"entity.supervisor"});
        xLabel4.setExpression("#{entity.supervisor.profession}");
        xLabel4.setName("entity.supervisor.profession"); // NOI18N
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel3.add(xLabel4);

        xLabel5.setCaption("PRC No");
        xLabel5.setDepends(new String[] {"entity.supervisor"});
        xLabel5.setExpression("#{entity.supervisor.prcno}");
        xLabel5.setName("entity.supervisor.profession"); // NOI18N
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel3.add(xLabel5);

        xLabel6.setCaption("PTR No");
        xLabel6.setDepends(new String[] {"entity.supervisor"});
        xLabel6.setExpression("#{entity.supervisor.ptrno}");
        xLabel6.setName("entity.supervisor.profession"); // NOI18N
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel3.add(xLabel6);

        cTCIndividualEntryPage3.setCaption("Community Tax Certificate");
        cTCIndividualEntryPage3.setDepends(new String[] {"entity.supervisor"});
        cTCIndividualEntryPage3.setName("entity.supervisor.ctc"); // NOI18N
        cTCIndividualEntryPage3.setPreferredSize(new java.awt.Dimension(0, 69));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cTCIndividualEntryPage3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cTCIndividualEntryPage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder5 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder5.setTitle("Architect/Civil Engineer In-charge of plans and specification");
        jPanel7.setBorder(xTitledBorder5);

        xFormPanel6.setCaptionWidth(180);

        xLookupField5.setCaption("Design (architect/civilengineer)");
        xLookupField5.setExpression("#{entity.designer.name}");
        xLookupField5.setHandler("lookupDesigner");
        xLookupField5.setName("entity.designer"); // NOI18N
        xLookupField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel6.add(xLookupField5);

        xLabel7.setCaption("Profession");
        xLabel7.setDepends(new String[] {"entity.designer"});
        xLabel7.setExpression("#{entity.designer.profession}");
        xLabel7.setName("entity.designer.profession"); // NOI18N
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel6.add(xLabel7);

        xLabel8.setCaption("PRC No");
        xLabel8.setDepends(new String[] {"entity.designer"});
        xLabel8.setExpression("#{entity.designer.prcno}");
        xLabel8.setName("entity.designer.prcno"); // NOI18N
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel6.add(xLabel8);

        xLabel9.setCaption("PTR No");
        xLabel9.setDepends(new String[] {"entity.designer"});
        xLabel9.setExpression("#{entity.designer.ptrno}");
        xLabel9.setName("entity.designer.ptrno"); // NOI18N
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel6.add(xLabel9);

        cTCIndividualEntryPage4.setCaption("Community Tax Certificate");
        cTCIndividualEntryPage4.setDepends(new String[] {"entity.designer"});
        cTCIndividualEntryPage4.setName("entity.supervisor.ctc"); // NOI18N
        cTCIndividualEntryPage4.setPreferredSize(new java.awt.Dimension(0, 69));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cTCIndividualEntryPage4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cTCIndividualEntryPage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        xTabbedPane1.addTab("Professionals", jPanel5);

        add(xTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.etracs.components.CTCIndividualEntryPage cTCIndividualEntryPage1;
    private com.rameses.etracs.components.CTCIndividualEntryPage cTCIndividualEntryPage2;
    private com.rameses.etracs.components.CTCIndividualEntryPage cTCIndividualEntryPage3;
    private com.rameses.etracs.components.CTCIndividualEntryPage cTCIndividualEntryPage4;
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.enterprise.components.LOVList lOVList1;
    private com.rameses.gov.etracs.obo.components.OboAddress oboAddress1;
    private com.rameses.entity.components.OrgTypeList orgTypeList1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XFormPanel xFormPanel7;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    private com.rameses.rcp.control.XLookupField xLookupField4;
    private com.rameses.rcp.control.XLookupField xLookupField5;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XPanel xPanel3;
    private com.rameses.rcp.control.XTabbedPane xTabbedPane1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
}
