/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.enterprise.treasury.components;

import com.rameses.common.MethodResolver;
import com.rameses.rcp.control.XComponentPanel;
import com.rameses.rcp.ui.annotations.ComponentBean;
import javax.swing.SwingConstants;

/**
 *
 * @author dell
 */
@ComponentBean("com.rameses.enterprise.treasury.components.CashDenominationModel")
public class CashDenomination extends XComponentPanel {

    private String formatter;
    private String amountField;      //This is the amount that needs breakdown
    private String handler;
    
    /**
     * Creates new form Denomination
     */
    public CashDenomination() {
        initComponents();
        int1000.setHorizontalAlignment(SwingConstants.CENTER);
        int500.setHorizontalAlignment(SwingConstants.CENTER);
        int200.setHorizontalAlignment(SwingConstants.CENTER);
        int100.setHorizontalAlignment(SwingConstants.CENTER);
        int50.setHorizontalAlignment(SwingConstants.CENTER);
        int10.setHorizontalAlignment(SwingConstants.CENTER);
        int20.setHorizontalAlignment(SwingConstants.CENTER);
        int5.setHorizontalAlignment(SwingConstants.CENTER);
        int1.setHorizontalAlignment(SwingConstants.CENTER);
        intc50.setHorizontalAlignment(SwingConstants.CENTER);
        intc25.setHorizontalAlignment(SwingConstants.CENTER); 
        intc10.setHorizontalAlignment(SwingConstants.CENTER);
        intc05.setHorizontalAlignment(SwingConstants.CENTER);
        intc01.setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        xLabel17 = new com.rameses.rcp.control.XLabel();
        xLabel18 = new com.rameses.rcp.control.XLabel();
        jPanel4 = new javax.swing.JPanel();
        xFormPanel12 = new com.rameses.rcp.control.XFormPanel();
        int1000 = new com.rameses.rcp.control.XIntegerField();
        int500 = new com.rameses.rcp.control.XIntegerField();
        int200 = new com.rameses.rcp.control.XIntegerField();
        int100 = new com.rameses.rcp.control.XIntegerField();
        int50 = new com.rameses.rcp.control.XIntegerField();
        int20 = new com.rameses.rcp.control.XIntegerField();
        int10 = new com.rameses.rcp.control.XIntegerField();
        int5 = new com.rameses.rcp.control.XIntegerField();
        int1 = new com.rameses.rcp.control.XIntegerField();
        intc50 = new com.rameses.rcp.control.XIntegerField();
        intc25 = new com.rameses.rcp.control.XIntegerField();
        intc10 = new com.rameses.rcp.control.XIntegerField();
        intc05 = new com.rameses.rcp.control.XIntegerField();
        intc01 = new com.rameses.rcp.control.XIntegerField();
        xFormPanel13 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel15 = new com.rameses.rcp.control.XLabel();
        xLabel16 = new com.rameses.rcp.control.XLabel();
        formfooter = new com.rameses.rcp.control.XFormPanel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel11 = new com.rameses.rcp.control.XLabel();

        setLayout(new com.rameses.rcp.control.layout.XLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new com.rameses.rcp.control.layout.YLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        xLabel17.setExpression("Qty");
        xLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xLabel17.setFontStyle("font-weight: bold;");
        jPanel1.add(xLabel17);

        xLabel18.setExpression("Totals");
        xLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        xLabel18.setFontStyle("font-weight: bold;");
        jPanel1.add(xLabel18);

        jPanel3.add(jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        xFormPanel12.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel12.setPreferredSize(new java.awt.Dimension(125, 306));

        int1000.setCaption("1000");
        int1000.setName("qty1000"); // NOI18N
        int1000.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int1000.setCaptionWidth(60);
        int1000.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int1000);

        int500.setCaption(" 500");
        int500.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int500.setCaptionWidth(60);
        int500.setName("qty500"); // NOI18N
        int500.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int500);

        int200.setCaption(" 200");
        int200.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int200.setCaptionWidth(60);
        int200.setName("qty200"); // NOI18N
        int200.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int200);

        int100.setCaption(" 100");
        int100.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int100.setCaptionWidth(60);
        int100.setName("qty100"); // NOI18N
        int100.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int100);

        int50.setCaption("  50");
        int50.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int50.setCaptionWidth(60);
        int50.setName("qty50"); // NOI18N
        int50.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int50);

        int20.setCaption("  20");
        int20.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int20.setCaptionWidth(60);
        int20.setName("qty20"); // NOI18N
        int20.setPreferredSize(new java.awt.Dimension(0, 20));
        int20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int20ActionPerformed(evt);
            }
        });
        xFormPanel12.add(int20);

        int10.setCaption("  10");
        int10.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int10.setCaptionWidth(60);
        int10.setName("qty10"); // NOI18N
        int10.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int10);

        int5.setCaption("   5");
        int5.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int5.setCaptionWidth(60);
        int5.setName("qty5"); // NOI18N
        int5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int5);

        int1.setCaption("   1");
        int1.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        int1.setCaptionWidth(60);
        int1.setName("qty1"); // NOI18N
        int1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(int1);

        intc50.setCaption("0.50");
        intc50.setName("qtyc50"); // NOI18N
        intc50.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        intc50.setCaptionWidth(60);
        intc50.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(intc50);

        intc25.setCaption("0.25");
        intc25.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        intc25.setCaptionWidth(60);
        intc25.setName("qtyc25"); // NOI18N
        intc25.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(intc25);

        intc10.setCaption("0.10");
        intc10.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        intc10.setCaptionWidth(60);
        intc10.setName("qtyc10"); // NOI18N
        intc10.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(intc10);

        intc05.setCaption("0.05");
        intc05.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        intc05.setCaptionWidth(60);
        intc05.setName("qtyc05"); // NOI18N
        intc05.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(intc05);

        intc01.setCaption("0.01");
        intc01.setCaptionFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        intc01.setCaptionWidth(60);
        intc01.setName("qtyc01"); // NOI18N
        intc01.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel12.add(intc01);

        jPanel4.add(xFormPanel12, java.awt.BorderLayout.WEST);

        xFormPanel13.setPadding(new java.awt.Insets(0, 2, 0, 0));
        xFormPanel13.setPreferredSize(new java.awt.Dimension(100, 306));

        xLabel1.setDepends(new String[] {"qty1000"});
        xLabel1.setExpression("#{d1000}");
        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel1.setNumberFormat("#,##0.00");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel1.setShowCaption(false);
        xFormPanel13.add(xLabel1);

        xLabel3.setDepends(new String[] {"qty500"});
        xLabel3.setExpression("#{d500}");
        xLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel3.setNumberFormat("#,##0.00");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel3.setShowCaption(false);
        xFormPanel13.add(xLabel3);

        xLabel2.setDepends(new String[] {"qty200"});
        xLabel2.setExpression("#{d200}");
        xLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel2.setNumberFormat("#,##0.00");
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel2.setShowCaption(false);
        xFormPanel13.add(xLabel2);

        xLabel4.setDepends(new String[] {"qty100"});
        xLabel4.setExpression("#{d100}");
        xLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel4.setNumberFormat("#,##0.00");
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel4.setShowCaption(false);
        xFormPanel13.add(xLabel4);

        xLabel5.setDepends(new String[] {"qty50"});
        xLabel5.setExpression("#{d50}");
        xLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel5.setNumberFormat("#,##0.00");
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel5.setShowCaption(false);
        xFormPanel13.add(xLabel5);

        xLabel6.setDepends(new String[] {"qty20"});
        xLabel6.setExpression("#{d20}");
        xLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel6.setNumberFormat("#,##0.00");
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel6.setShowCaption(false);
        xFormPanel13.add(xLabel6);

        xLabel7.setDepends(new String[] {"qty10"});
        xLabel7.setExpression("#{d10}");
        xLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel7.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel7.setNumberFormat("#,##0.00");
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel7.setShowCaption(false);
        xFormPanel13.add(xLabel7);

        xLabel8.setDepends(new String[] {"qty5"});
        xLabel8.setExpression("#{d5}");
        xLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel8.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel8.setNumberFormat("#,##0.00");
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel8.setShowCaption(false);
        xFormPanel13.add(xLabel8);

        xLabel9.setDepends(new String[] {"qty1"});
        xLabel9.setExpression("#{d1}");
        xLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel9.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel9.setNumberFormat("#,##0.00");
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel9.setShowCaption(false);
        xFormPanel13.add(xLabel9);

        xLabel12.setDepends(new String[] {"qtyc50"});
        xLabel12.setExpression("#{dc50}");
        xLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel12.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel12.setNumberFormat("#,##0.00");
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel12.setShowCaption(false);
        xFormPanel13.add(xLabel12);

        xLabel13.setDepends(new String[] {"qtyc25"});
        xLabel13.setExpression("#{dc25}");
        xLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel13.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel13.setNumberFormat("#,##0.00");
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel13.setShowCaption(false);
        xFormPanel13.add(xLabel13);

        xLabel14.setDepends(new String[] {"qtyc10"});
        xLabel14.setExpression("#{dc10}");
        xLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel14.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel14.setNumberFormat("#,##0.00");
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel14.setShowCaption(false);
        xFormPanel13.add(xLabel14);

        xLabel15.setDepends(new String[] {"qtyc05"});
        xLabel15.setExpression("#{dc05}");
        xLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel15.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel15.setNumberFormat("#,##0.00");
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel15.setShowCaption(false);
        xFormPanel13.add(xLabel15);

        xLabel16.setDepends(new String[] {"qtyc01"});
        xLabel16.setExpression("#{dc01}");
        xLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel16.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel16.setNumberFormat("#,##0.00");
        xLabel16.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel16.setShowCaption(false);
        xFormPanel13.add(xLabel16);

        jPanel4.add(xFormPanel13, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel4);

        formfooter.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formfooter.setPadding(new java.awt.Insets(5, 0, 0, 0));

        xLabel10.setCaption("Total Breakdown");
        xLabel10.setDepends(new String[] {"qty1"});
        xLabel10.setExpression("#{total}");
        xLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel10.setCaptionWidth(100);
        xLabel10.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel10.setNumberFormat("#,##0.00");
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 20));
        formfooter.add(xLabel10);

        xLabel11.setCaption("Cash Remaining");
        xLabel11.setDepends(new String[] {"qty1"});
        xLabel11.setExpression("#{cashremaining}");
        xLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel11.setCaptionWidth(100);
        xLabel11.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        xLabel11.setNumberFormat("#,##0.00");
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 20));
        formfooter.add(xLabel11);

        jPanel3.add(formfooter);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void int20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_int20ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel formfooter;
    private com.rameses.rcp.control.XIntegerField int1;
    private com.rameses.rcp.control.XIntegerField int10;
    private com.rameses.rcp.control.XIntegerField int100;
    private com.rameses.rcp.control.XIntegerField int1000;
    private com.rameses.rcp.control.XIntegerField int20;
    private com.rameses.rcp.control.XIntegerField int200;
    private com.rameses.rcp.control.XIntegerField int5;
    private com.rameses.rcp.control.XIntegerField int50;
    private com.rameses.rcp.control.XIntegerField int500;
    private com.rameses.rcp.control.XIntegerField intc01;
    private com.rameses.rcp.control.XIntegerField intc05;
    private com.rameses.rcp.control.XIntegerField intc10;
    private com.rameses.rcp.control.XIntegerField intc25;
    private com.rameses.rcp.control.XIntegerField intc50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel12;
    private com.rameses.rcp.control.XFormPanel xFormPanel13;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel16;
    private com.rameses.rcp.control.XLabel xLabel17;
    private com.rameses.rcp.control.XLabel xLabel18;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void afterLoad() {
        com.rameses.rcp.common.ComponentBean cb = (com.rameses.rcp.common.ComponentBean)getComponentBean();
        if( getFormatter()!=null ) {
            cb.setProperty("formatter", getProperty(getFormatter()));
        }
        if( getAmountField()!=null) {
            cb.setProperty("amount", getProperty(getAmountField()));
        }
        if( getHandler()!=null) {
            cb.setProperty("handler", getProperty(getHandler()));
        }
        try {
            MethodResolver mr = MethodResolver.getInstance();
            mr.invoke(cb, "init", null);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void afterRefresh() {
        com.rameses.rcp.common.ComponentBean cb = (com.rameses.rcp.common.ComponentBean)getComponentBean();
         if( getAmountField()!=null) {
            cb.setProperty("amount", getProperty(getAmountField()));
        }
        try {
            MethodResolver mr = MethodResolver.getInstance();
            mr.invoke(cb, "init", null);
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }

    
    
    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        int1000.setEnabled(enabled);
        int500.setEnabled(enabled);
        int200.setEnabled(enabled);
        int100.setEnabled(enabled);
        int50.setEnabled(enabled);
        int10.setEnabled(enabled);
        int20.setEnabled(enabled);
        int5.setEnabled(enabled);
        int1.setEnabled(enabled);
        intc50.setEnabled(enabled);
        intc25.setEnabled(enabled); 
        intc10.setEnabled(enabled);
        intc05.setEnabled(enabled);
        intc01.setEnabled(enabled);
    }

    public String getAmountField() {
        return amountField;
    }

    public void setAmountField(String amount) {
        this.amountField = amount;
    }

    
    public String getFormatter() {
        return formatter;
    }

    public void setFormatter(String formatter) {
        this.formatter = formatter;
    }
    
    public boolean isFooterVisible() {
        return (formfooter == null ? formfooter.isVisible() : true); 
    }
    public void setFooterVisible( boolean visible ) {
        if ( formfooter != null ) {
            formfooter.setVisible( visible ); 
        }
    }

    /**
     * @return the handler
     */
    public String getHandler() {
        return handler;
    }

    /**
     * @param handler the handler to set
     */
    public void setHandler(String handler) {
        this.handler = handler;
    }
}
