/*
 * AddressField.java
 *
 * Created on March 30, 2014, 7:57 PM
 */

package com.rameses.enterprise.views;

/**
 *
 * @author  Elmo
 */
public class AddressComponent extends javax.swing.JPanel {
    
    /** Creates new form AddressField */
    public AddressComponent() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        jPanel1 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        xTextArea1.setEditable(false);
        xTextArea1.setName("entity.text"); // NOI18N
        xTextArea1.setShowCaption(false);
        jScrollPane1.setViewportView(xTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 1));
        jPanel1.setLayout(new java.awt.BorderLayout());

        xButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        xButton1.setName("editAddress"); // NOI18N
        xButton1.setPreferredSize(new java.awt.Dimension(30, 23));
        xButton1.setShowCaption(false);
        jPanel1.add(xButton1, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
