/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.bpls.view;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author dell
 */
@Template(OKCancelPage.class)
public class CapturePermitPage extends javax.swing.JPanel {

    /**
     * Creates new form CapturePermitPage
     */
    public CapturePermitPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextField2 = new com.rameses.rcp.control.XTextField();

        xTextField1.setCaption("Permit No");
        xTextField1.setCaptionFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField1.setCaptionWidth(120);
        xTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField1.setName("entity.permitno"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField1);

        xDateField1.setCaption("Date Issued");
        xDateField1.setCaptionFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xDateField1.setCaptionWidth(120);
        xDateField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xDateField1.setName("entity.dtissued"); // NOI18N
        xFormPanel1.add(xDateField1);

        xTextField2.setCaption("Plate No");
        xTextField2.setCaptionFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField2.setCaptionWidth(120);
        xTextField2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField2.setName("entity.plateno"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
