/*
 * BorrowerParentPage.java
 *
 * Created on September 10, 2013, 1:09 PM
 */

package com.rameses.clfc.borrower;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  Rameses
 */
@StyleSheet
public class BorrowerParentsPage extends javax.swing.JPanel 
{
    
    public BorrowerParentsPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        xTextArea2 = new com.rameses.rcp.control.XTextArea();

        setLayout(new java.awt.BorderLayout());

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("  General Information  ");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setPadding(new java.awt.Insets(10, 15, 10, 20));

        xFormPanel2.setCellspacing(30);
        xFormPanel2.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel2.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.setShowCaption(false);
        xTextField4.setCaption("Father's Name");
        xTextField4.setCaptionWidth(100);
        xTextField4.setHint("Father's Name");
        xTextField4.setIndex(-10);
        xTextField4.setName("entity.fathername");
        xTextField4.setPreferredSize(new java.awt.Dimension(250, 20));
        xFormPanel2.add(xTextField4);

        xIntegerField1.setCaption("Age");
        xIntegerField1.setCaptionWidth(50);
        xIntegerField1.setName("entity.fatherage");
        xIntegerField1.setPreferredSize(new java.awt.Dimension(50, 20));
        xFormPanel2.add(xIntegerField1);

        xFormPanel1.add(xFormPanel2);

        xFormPanel3.setCellspacing(30);
        xFormPanel3.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel3.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel3.setPreferredSize(new java.awt.Dimension(0, 22));
        xFormPanel3.setShowCaption(false);
        xTextField5.setCaption("Mother's Name");
        xTextField5.setCaptionWidth(100);
        xTextField5.setHint("Mother's Name");
        xTextField5.setName("entity.mothername");
        xTextField5.setPreferredSize(new java.awt.Dimension(250, 20));
        xFormPanel3.add(xTextField5);

        xIntegerField2.setCaption("Age");
        xIntegerField2.setCaptionWidth(50);
        xIntegerField2.setName("entity.motherage");
        xIntegerField2.setPreferredSize(new java.awt.Dimension(50, 20));
        xFormPanel3.add(xIntegerField2);

        xFormPanel1.add(xFormPanel3);

        xTextField3.setCaption("Address");
        xTextField3.setCaptionWidth(100);
        xTextField3.setHint("Address");
        xTextField3.setName("entity.address");
        xTextField3.setPreferredSize(new java.awt.Dimension(380, 20));
        xFormPanel1.add(xTextField3);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(380, 50));
        xTextArea2.setCaption("Remarks");
        xTextArea2.setCaptionWidth(100);
        xTextArea2.setName("entity.remarks");
        xTextArea2.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane2.setViewportView(xTextArea2);

        xFormPanel1.add(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        add(jPanel2, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XTextArea xTextArea2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    // End of variables declaration//GEN-END:variables
    
}
