/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.entity.components;

import com.rameses.rcp.control.XComponentPanel;
import com.rameses.rcp.ui.annotations.ComponentBean;

/**
 *
 * @author dell
 */
@ComponentBean("com.rameses.entity.components.OrgTypeListModel")
public class OrgTypeList extends XComponentPanel {

    /**
     * Creates new form OrgTypeList
     */
    public OrgTypeList() {
        initComponents();
    }

    
    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        cboOrgType.setEnabled(enabled);
    }

    public void setEditable(boolean b) {
        setEnabled(b);
    }
    
    public boolean isEditable() {
        return this.isEnabled();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboOrgType = new com.rameses.rcp.control.XComboBox();

        setLayout(new java.awt.BorderLayout());

        cboOrgType.setAllowNull(false);
        cboOrgType.setCaption("Org Type");
        cboOrgType.setExpression("#{item.value}");
        cboOrgType.setItemKey("key");
        cboOrgType.setItems("orgTypes");
        cboOrgType.setName("orgtype"); // NOI18N
        cboOrgType.setPreferredSize(new java.awt.Dimension(250, 22));
        cboOrgType.setRequired(true);
        add(cboOrgType, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox cboOrgType;
    // End of variables declaration//GEN-END:variables
}
